Repository deadbelly/breathEZ, pull requests merged in 2021-02, with the labels that each got.

#23 Ec/feature/error msg
  src/Components/Error/Error.css
  src/Components/Error/Error.js
Labels: enhancement

#26 Ec/feature header
  src/Components/Header/Header.js
Labels: bug, enhancement

#31 Feature/render routes
  package-lock.json
  src/Components/App/App.js
  src/Components/Faq/Faq.js
  src/Components/Header/Header.js
  src/Components/Selector/Selector.js
Labels: enhancement

#32 Tm/feature/style header faq
  package-lock.json
  package.json
  src/Components/Faq/Faq.css
  src/Components/Faq/Faq.js
  src/Components/Faq/_Faq.scss
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Header/_Header.scss
  src/assets/AQI-chart.jpg
  src/assets/maddison-mcmurrin-GDumtPpJsT4-unsplash.jpg
  src/index.css
  src/index.js
  src/index.scss
Labels: Styling

#33 Feature/select tests
  assets/AQI-chart.jpg
  cypress.json
  cypress/fixtures/blackfootData.json
  cypress/fixtures/coCities.json
  cypress/fixtures/denverData.json
  cypress/fixtures/idCities.json
  cypress/fixtures/statesData.json
  cypress/integration/faq-spec.js
  cypress/integration/main-view-spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/Components/Faq/Faq.css
  src/Components/Faq/Faq.js
  src/Components/Faq/_Faq.scss
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Header/_Header.scss
  src/assets/maddison-mcmurrin-GDumtPpJsT4-unsplash.jpg
  src/index.css
  src/index.js
  src/index.scss
Labels: testing

#44 Ec/feature/test faq home links
  cypress/integration/main-view-spec.js
Labels: testing

#45 Ec/feature/test data
  cypress/fixtures/academyData.json
  cypress/fixtures/coCities.json
  cypress/fixtures/haileyData.json
  cypress/fixtures/idCities.json
  cypress/fixtures/salmonData.json
  cypress/integration/main-view-spec.js
Labels: testing
